/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Q0CeLIfONaY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Badge } from "@/components/ui/badge"

export function GoDeep() {
  return (
    (<div className="flex flex-col items-center w-full h-screen">
      <div className="relative w-full h-2/3">
        <img src="/placeholder.svg" alt="Map" className="object-cover w-full h-full" />
        <div className="absolute top-4 left-4 right-4">
          <div className="flex items-center w-full p-2 bg-white rounded-full shadow-md">
            <MenuIcon className="w-6 h-6 mr-2" />
            <input
              type="text"
              placeholder="Where to...."
              className="flex-1 px-2 py-1 text-sm border-none rounded-full focus:outline-none" />
            <SearchIcon className="w-6 h-6 ml-2" />
          </div>
        </div>
      </div>
      <div className="w-full p-4 bg-white">
        <div className="grid gap-4">
          <div className="flex items-center justify-between p-2 border-b">
            <div>

            <span>Auto</span>
            <Badge className="mx-4 " variant="secondary">4min.</Badge>
            </div>
            <img src="/placeholder.svg" alt="Auto" className="w-8 h-8" />
          </div>
          <div className="flex items-center justify-between p-2 border-b">
            <div>
              <span>Bike</span>
              <Badge className="mx-4" variant="secondary">2min.</Badge>
            </div>
            <img src="/placeholder.svg" alt="Bike" className="w-8 h-8" />
          </div>
          <div className="flex items-center justify-between p-2 border-b">
            <div>
              <span>Mini</span>
              <Badge className="mx-4" variant="secondary">5min.</Badge>
            </div>
            <img src="/placeholder.svg" alt="Mini" className="w-8 h-8" />
          </div>
          <div className="flex items-center justify-between p-2 border-b">
            <div>
              <span>SUV</span>
              <Badge className="mx-4" variant="secondary">6min.</Badge>
            </div>
            <img src="/placeholder.svg" alt="SUV" className="w-8 h-8" />
          </div>
          <div className="flex items-center justify-between p-2 border-b">
            <div>
              <span>Sedan</span>
              <Badge className="mx-4" variant="secondary">9min.</Badge>
            </div>
            <img src="/placeholder.svg" alt="Sedan" className="w-8 h-8" />
          </div>
        </div>
      </div>
    </div>)
  );
}

function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}
